### ISSUE TITLE
CSS box-sizing attribute for .jqstooltip lacks an explicit setting

### ISSUE THREAD

**Issue by aleksmsd** [gwatts/jquery.sparkline#202]
Version: 2.1.2
jQuery Version: v1.12.4

Hey!
I noticed a small issue with the default tooltip class.
Initially my tooltips were rendering out like below
![image](https://user-images.githubusercontent.com/25099261/47584791-6b6fe700-d910-11e8-8e4d-d2a2b5584651.png)

After looking into it a bit more, it looks like the `.jqstooltip` class was inheriting from some *-setting in my `normalize.css`:
```css
* {
  box-sizing: border-box;
}
```

So I set the following:
```css
.jqstooltip {
  box-sizing: content-box;
}
```

And now it's all good again!
![image](https://user-images.githubusercontent.com/25099261/47585100-2e582480-d911-11e8-85ef-76508f04f164.png)

So my request on this issue, can we get the library to have this `box-sizing` attribute explicitly set out of the box?

Thank you!
