### ISSUE TITLE
Bootstrap box-sizing causing tooltip issues

### ISSUE THREAD

**Issue by chrisfraser** [gwatts/jquery.sparkline#89]
Globally setting box-sizing to border-box causes tooltip to be displayed incorrectly. This can be fixed by the following css after bootstrap. This may become an issue as box-sizing is more frequently used.

``` css
.jqstooltip{
    box-sizing: content-box;
}
```

![image](https://f.cloud.github.com/assets/929529/954872/e97913cc-041f-11e3-82b1-6d68afd3e865.png)
